language: ruby
sudo: false
rvm:
  - '2.4.2'
  - '2.3.4'
  - '1.9.3'
  - 'jruby'
  - 'rbx'
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 69a23bee43b8c53271b1a6fbe18b6167de91a06d66ab19908dd52f73158ab71b
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
    - rvm: '1.9.3'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ghostscript
